spring.application.name=devmatch

spring.profiles.active=dev

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=DevMatch
info.app.description=Freelance marketplace backend built with Spring Boot
info.app.version=1.0.0

